apiVersion: apps/v1
kind: Deployment
metadata:
  name: sec-redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sec-redis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sec-redis
    spec:
      containers:
      - env:
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        image: redis:latest  # Redis 이미지
        imagePullPolicy: Always
        name: sec-redis
        ports:
        - containerPort: 6379
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 1000Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
